# Path: core/alchemist/elara/scanner/patterns/__init__.py
# -------------------------------------------------------

from .sigils import SIGIL_OR_DOCSTRING_REGEX, WHITESPACE_CONTROL_REGEX
from .alien import ALIEN_JS_REGEX, ALIEN_ARROW_REGEX, ALIEN_NESTING_REGEX, ALIEN_RUST_REGEX, ALIEN_GO_REGEX, AMNESTY_VETO_REGEX, GNOSTIC_PREFIX, GNOSTIC_DOMAINS

__all__ =[
    "SIGIL_OR_DOCSTRING_REGEX", "WHITESPACE_CONTROL_REGEX",
    "ALIEN_JS_REGEX", "ALIEN_ARROW_REGEX", "ALIEN_NESTING_REGEX",
    "ALIEN_RUST_REGEX", "ALIEN_GO_REGEX", "AMNESTY_VETO_REGEX",
    "GNOSTIC_PREFIX", "GNOSTIC_DOMAINS"
]