# Path: creator/io_controller/facade.py
# -------------------------------------


from __future__ import annotations

import os
import sys
import time
import hashlib
import base64
import binascii
import subprocess
import shutil
import mimetypes
import re
import threading
import unicodedata
import gc
from pathlib import Path
from typing import Union, Dict, Any, TYPE_CHECKING, Tuple, Optional, List, Final

# --- THE DIVINE UPLINKS ---
from .path_alchemist import PathAlchemist
from .security import SecurityWards
from .transaction_router import TransactionRouter
from ..writer.normalizer import ContentNormalizer
from ..writer.security import SecretSentinel
from ..writer.differential import DifferentialEngine
from ..writer.symbiote import GnosticSymbiote
from ...contracts.data_contracts import GnosticWriteResult, InscriptionAction
from ...contracts.heresy_contracts import ArtisanHeresy, HeresySeverity
from ...logger import Scribe
from ...core.runtime.vessels import GnosticSovereignDict

# === THE ACHRONAL LEDGER IMPORTS ===
from ...creator.io_controller.trash import TrashManager
from ...core.state import ActiveLedger
from ...core.state.contracts import LedgerEntry, LedgerOperation, InverseOp

if TYPE_CHECKING:
    from ..registers import QuantumRegisters
    from ...core.sanctum.base import SanctumInterface

Logger = Scribe("IOConductor")


class IOConductor:
    """
    =================================================================================
    == THE GOD-ENGINE OF CAUSALITY (V-Ω-TOTALITY-V1000000-KINETIC-CORE-HEALED)     ==
    =================================================================================
    LIF: ∞ | ROLE: KINETIC_IO_ORCHESTRATOR | RANK: OMEGA_SOVEREIGN_PRIME
    AUTH: Ω_CONDUCTOR_V1M_ATOMIC_PERSISTENCE_FINALIS_2026

    The supreme authority for physical and virtual manifestation. It transmutes
    Gnostic Intent into Substance by commanding the Multiversal Driver Lattice.
    It is mathematically warded against Race Conditions, Power Failures, and
    Spatial Drift.

    ### THE PANTHEON OF LEGENDARY ASCENSIONS:
    1.  **VFS Transparent Routing:** Silently diverts all I/O to RAM if `registers.vfs`
        is manifest, guaranteeing zero physical side-effects during simulations.
    2.  **Achronal Spatial Anchoring (THE CURE):** Binds `__current_dir__` to the
        alchemical context *before* path transmutation, completely annihilating
        the Phantom Sanctum anomaly for nested `logic.weave` calls.
    3.  **The Phantom Ward (THE MASTER CURE):** Instantly recognizes the `__phantom_weave_`
        file signatures generated by the `LogicWeaver`. It bypasses physical I/O to
        evaluate the content, firing the side-effect and returning a `SKIPPED` artifact.
    4.  **Target Resolution Rectification (THE FIX):** Eliminates the Staging Divergence.
        Ensures physical writes target the **REAL DESTINATION** so that `TransactionManager`
        can correctly backup the original state, rather than writing to a ghost directory
        that never gets merged.
    5.  **Quantum Atomic Persistence:** Writes to a hidden `.tmp` file, calls
        `os.fsync()` to flush hardware buffers, and uses atomic `os.replace()`,
        ensuring 100% ACID compliance against kernel panics.
    6.  **WinError 32 Phalanx:** Uses exponential micro-jitter backoff to defeat
        transient Windows file locks caused by Windows Defender or indexing services.
    7.  **Idempotency Merkle-Gaze:** Hashes the fully transmuted content and compares
        it with the physical snapshot to bypass I/O if reality is already resonant.
    8.  **The Symbiotic Coalescence:** Intelligently maps `+=`, `^=`, and `~=`
        metadata flags to the `GnosticSymbiote` for non-destructive AST merging.
    9.  **The Shadow Revert (Ledger Vow):** Captures exact binary snapshots before
        any mutation, storing them in the `ActiveLedger` for flawless Undo capability.
    10. **Shannon Entropy Scrying:** Inline execution of `SecretSentinel` to scrub
        high-entropy leaks and API keys prior to physical disk contact.
    11. **The Auto-Import Healer:** Scans generated Python code for missing
        standard symbols (`os`, `sys`, `FastAPI`) and injects them autonomously.
    12. **Hyper-Diagnostic Logging:** Proclaims detailed trace telemetry when
        navigating complex nested transactions to illuminate the Void.
    =================================================================================
    """

    # [ASCENSION 3]: Homoglyph & Zero-Width Exorcist Map
    HOMOGLYPH_PATTERN: Final[re.Pattern] = re.compile(r'[\u200b\u200c\u200d\u2060\uFEFF]')

    # [ASCENSION 10]: THE AUTO-IMPORT GRIMOIRE
    IMPORT_HEALING_MAP: Final[Dict[str, str]] = {
        "BaseHTTPMiddleware": "from starlette.middleware.base import BaseHTTPMiddleware",
        "FastAPI": "from fastapi import FastAPI",
        "Depends": "from fastapi import Depends",
        "APIRouter": "from fastapi import APIRouter",
        "HTTPException": "from fastapi import HTTPException",
        "Request": "from fastapi import Request",
        "Response": "from fastapi import Response",
        "BaseModel": "from pydantic import BaseModel",
        "Field": "from pydantic import Field",
        "List": "from typing import List",
        "Dict": "from typing import Dict",
        "Optional": "from typing import Optional",
        "Any": "from typing import Any",
        "Path": "from pathlib import Path",
        "os": "import os",
        "sys": "import sys",
        "json": "import json",
        "time": "import time"
    }

    LFS_MASS_THRESHOLD: Final[int] = 50 * 1024 * 1024  # 50MB

    def __init__(self, registers: "QuantumRegisters"):
        """[THE RITE OF INCEPTION]"""
        self.regs = registers
        self.project_root = registers.project_root or Path.cwd()
        self.vfs = registers.vfs  # [ASCENSION 1]: The Virtual Reality Anchor

        # --- THE FORGING OF THE PANTHEON ---
        self.alchemist = PathAlchemist(registers.gnosis)
        self.security = SecurityWards()
        self.router = TransactionRouter(registers)
        self.normalizer = ContentNormalizer(is_windows=(os.name == 'nt'))
        self.differ = DifferentialEngine()
        self.symbiote = GnosticSymbiote()
        self.trash = TrashManager(self.project_root)

        # [ASCENSION 31]: Substrate Sensing
        self.is_windows = os.name == 'nt'
        self.is_wasm = os.environ.get('SCAFFOLD_ENV') == 'WASM' or sys.platform == 'emscripten'

        from ...core.alchemist import get_alchemist
        self.template_alchemist = get_alchemist()

        self._start_time = time.monotonic()
        self._io_lock = threading.RLock()

        Logger.verbose(
            f"IOConductor resonant. Substrate: {'VFS_RAM' if self.vfs else ('ETHER' if self.is_wasm else 'IRON')}")

    def write(self, logical_path: Union[str, Path], content: Union[str, bytes],
              metadata: Dict[str, Any]) -> GnosticWriteResult:
        """
        =================================================================================
        == THE OMEGA INSCRIPTION RITE: TOTALITY (V-Ω-VMAX-BLURRY-MATTER-WARD)          ==
        =================================================================================
        LIF: ∞^∞ | ROLE: KINETIC_MATTER_MANIFESTOR | RANK: OMEGA_SOVEREIGN_PRIME
        AUTH_CODE: Ω_WRITE_VMAX_TOPOLOGICAL_PURITY_FINALIS_2026

        [THE MANIFESTO]
        The supreme definitive authority for physical manifestation. This version
        righteously implements the **Blurry Matter Inquest**, mathematically
        forbidding the materialization of unresolved sigils ({{, }}) as filesystem
        topography. It provides high-fidelity forensic radiation in the event of
        a geometric fracture.

        ### THE PANTHEON OF 12 LEGENDARY ASCENSIONS:
        1.  **The Blurry Matter Inquest (THE MASTER CURE):** Surgically scans the
            transmuted path for SGF/Jinja residue. If '{{' or '}}' is perceived,
            the Hand is stayed, and a Critical Heresy is waked.
        2.  **Achronal Retinal Radiation:** If a Blurry Path is detected, it
            blasts a high-intensity, unbuffered Red-Aura proclamation to
            sys.stderr, ensuring the Architect perceives the fracture instantly.
        3.  **Next.js Dynamic Bracketing Amnesty:** Intelligently permits
            '[[...]]' and '[id]' patterns, recognizing them as legitimate
            Ocular Topography rather than unresolved Gnosis.
        4.  **Achronal Spatial Anchoring:** Binds `__current_file__` and
            `__current_dir__` context *before* path transmutation, annihilating
            the Phantom Sanctum anomaly.
        5.  **The Phantom Ward (SIDE-EFFECT SUTURE):** Detects `__phantom_weave_`
            signatures to execute side-effect logic while bypassing physical I/O.
        6.  **Quantum Atomic Persistence:** Writes to a hidden `.tmp` file, calls
            `os.fsync()` to flush hardware buffers, and uses atomic `os.replace()`.
        7.  **WinError 32 Phalanx:** Employs exponential micro-jitter backoff to
            defeat transient Windows file locks during the atomic swap.
        8.  **NoneType Content Sarcophagus:** Transmutes Null-content into
            bit-perfect empty strings, mathematically forbidding write fractures.
        9.  **Idempotency Merkle-Gaze:** Hashes the fully transmuted content to
            bypass I/O if the Iron already reflects the willed Gnosis.
        10. **The Auto-Import Healer:** Scans generated Python code for missing
            standard symbols (FastAPI, Pydantic) and injects them autonomously.
        11. **Trace ID Silver-Cord Suture:** Force-binds the active session
            Trace ID to the metadata for 1:1 forensic causality in the HUD.
        12. **The Finality Vow:** A mathematical guarantee of an unbreakable,
            transaction-aligned, and sigil-free physical form.
        =================================================================================
        """
        import time
        import os
        import sys
        import hashlib
        import base64
        import binascii
        import uuid
        import unicodedata
        import re
        from pathlib import Path
        from ...contracts.data_contracts import GnosticWriteResult, InscriptionAction
        from ...contracts.heresy_contracts import HeresySeverity, ArtisanHeresy
        from ...core.state.contracts import LedgerEntry, LedgerOperation, InverseOp
        from ...core.state import ActiveLedger

        _start_ns = time.perf_counter_ns()
        trace_id = getattr(self.regs, 'trace_id', 'tr-void')

        # --- MOVEMENT 0: GEOMETRIC ANCHORING ---
        path_str = str(logical_path).replace('\\', '/')
        if path_str.startswith('./'):
            path_str = path_str[2:]

        if not path_str or path_str == '.':
            return GnosticWriteResult(success=False, path=Path("VOID"), action_taken=InscriptionAction.FAILED_IO)

        with self._io_lock:
            try:
                # =========================================================================
                # == [ASCENSION 2]: ACHRONAL SPATIAL ANCHORING                           ==
                # =========================================================================
                local_gnosis = self.regs.gnosis.copy()
                local_gnosis["__current_file__"] = path_str

                parent_dir_str = str(Path(path_str).parent).replace('\\', '/')
                if parent_dir_str == ".": parent_dir_str = ""

                local_gnosis["__current_dir__"] = parent_dir_str
                local_gnosis["__import_anchor__"] = parent_dir_str
                local_gnosis["__project_root__"] = str(self.project_root.resolve()).replace('\\', '/')

                # 1. ALCHEMICAL PATH TRANSMUTATION
                transmuted_path = self.alchemist.transmute(path_str, context_override=local_gnosis)

                # =========================================================================
                # == [ASCENSION 5]: THE PHANTOM WARD                                     ==
                # =========================================================================
                if "__phantom_weave_" in transmuted_path:
                    try:
                        safe_content = "" if content is None else str(content)
                        self.template_alchemist.transmute(safe_content, local_gnosis)
                    except Exception as e:
                        Logger.error(f"Phantom Weave Fracture: {e}")

                    return GnosticWriteResult(
                        success=True, path=Path("VOID"), action_taken=InscriptionAction.SKIPPED,
                        bytes_written=0, metadata={"note": "Phantom Side-Effect Manifested"}
                    )

                # =========================================================================
                # == [ASCENSION 1 & 2]: THE BLURRY MATTER INQUEST (THE MASTER CURE)      ==
                # =========================================================================
                # [THE MANIFESTO]: We mathematically forbid "Blurry Matter" from touching Iron.
                # If sigils survive, it indicates a Gnostic Gap (Missing Variable).
                if "{{" in transmuted_path or "}}" in transmuted_path or "{%" in transmuted_path:
                    # 1. FORENSIC RED-SHIFT PROCLAMATION
                    RED = "\x1b[38;5;196;1m"
                    GOLD = "\x1b[38;5;220m"
                    RESET = "\x1b[0m"

                    sys.stderr.write(f"\n{RED}💀 [TOPOLOGICAL_COLLAPSE] CRITICAL GNOSTIC GAP DETECTED{RESET}\n")
                    sys.stderr.write(f"{RED}│{RESET} Trace ID: {GOLD}{trace_id}{RESET}\n")
                    sys.stderr.write(f"{RED}│{RESET} Locus:    {GOLD}{path_str}{RESET}\n")
                    sys.stderr.write(f"{RED}│{RESET} Residue:  {RED}{transmuted_path}{RESET}\n")
                    sys.stderr.write(f"{RED}└─ STATUS:   STRIKE ABORTED (Matter is Blurry){RESET}\n\n")
                    sys.stderr.flush()

                    # 2. HALT THE STRIKE
                    raise ArtisanHeresy(
                        f"Topological Collapse: Path '{path_str}' remains Blurry.",
                        details=f"Unresolved Residue: {transmuted_path}",
                        severity=HeresySeverity.CRITICAL,
                        suggestion="Check for hallucinated variables or missing imports in the blueprint."
                    )

                # 3. BOUNDARY JURISPRUDENCE (Normalization & Moat check)
                self.security.adjudicate_path(transmuted_path)

                # 4. METABOLIC MASS CHECK
                self.security.verify_metabolic_mass(content)

                # 5. SPATIOTEMPORAL RESOLUTION
                if self.vfs:
                    driver = None
                    physical_locus = transmuted_path
                else:
                    driver, physical_locus = self.router.resolve(transmuted_path)

                # --- MOVEMENT II: THE FORENSIC SNAPSHOT ---
                snapshot: Optional[bytes] = None
                if not self.vfs and driver and driver.exists(physical_locus):
                    try:
                        snapshot = driver.read_bytes(physical_locus)
                    except Exception:
                        pass

                # --- MOVEMENT III: THE LEDGER VOW ---
                inverse_op = (
                    InverseOp(op=LedgerOperation.WRITE_FILE,
                              params={"path": transmuted_path, "content_is_snapshot": True})
                    if snapshot is not None else
                    InverseOp(op=LedgerOperation.DELETE_FILE, params={"path": transmuted_path})
                )

                ActiveLedger.record(LedgerEntry(
                    actor="IOConductor", operation=LedgerOperation.WRITE_FILE,
                    forward_state={"path": transmuted_path, "driver": "VFS" if self.vfs else driver.kind.name},
                    inverse_action=inverse_op, snapshot_content=snapshot,
                    metadata={"trace_id": trace_id}
                ))

                # --- MOVEMENT IV: CONTENT TRANSMUTATION ---
                final_content_bytes = b""
                is_binary_flag = metadata.get('is_binary', False)
                is_binary_content = isinstance(content, bytes)

                from ...codex.loader.proxy import set_active_context, get_active_context
                prev_ctx = get_active_context()
                set_active_context(local_gnosis)

                try:
                    if is_binary_content:
                        final_content_bytes = content
                    elif is_binary_flag:
                        transmuted_str = self.template_alchemist.transmute(content, local_gnosis)
                        final_content_bytes = base64.b64decode(transmuted_str)
                    else:
                        # [ASCENSION 8]: NoneType Content Sarcophagus
                        safe_content = "" if content is None else str(content)
                        str_content = self.template_alchemist.transmute(safe_content, local_gnosis)

                        # [ASCENSION 10]: THE AUTO-IMPORT HEALER
                        if path_str.endswith('.py'):
                            str_content = self._heal_python_imports(str_content)

                        # Normalization
                        str_content = unicodedata.normalize('NFC', str_content).replace('\x00', '')

                        # [ASCENSION 10]: SECRET REDACTION
                        from ..writer.security import SecretSentinel
                        str_content = SecretSentinel.scan_and_warn(str_content, Path(transmuted_path).name)

                        str_content = self.normalizer.sanctify(Path(transmuted_path), str_content)
                        final_content_bytes = str_content.encode('utf-8')
                finally:
                    set_active_context(prev_ctx)

                new_hash = hashlib.sha256(final_content_bytes).hexdigest()

                # --- MOVEMENT V: THE KINETIC STRIKE (MATERIALIZATION) ---
                if self.regs.is_simulation:
                    return GnosticWriteResult(
                        success=True, path=Path(transmuted_path),
                        action_taken=InscriptionAction.DRY_RUN_CREATED,
                        bytes_written=len(final_content_bytes), gnostic_fingerprint=new_hash,
                        duration_ms=(time.perf_counter() - _start_ns) / 1_000_000
                    )

                action = InscriptionAction.CREATED
                if self.vfs:
                    vfs_path = str(transmuted_path).replace('\\', '/')
                    self.vfs.makedirs(str(Path(vfs_path).parent), recreate=True)
                    self.vfs.writebytes(vfs_path, final_content_bytes)
                else:
                    if self.regs.transaction:
                        self.regs.transaction.register_intent(self.regs.transaction.tx_id, Path(physical_locus),
                                                              'create')

                    # [ASCENSION 6 & 7]: QUANTUM ATOMIC PERSISTENCE & WINERROR 32 PHALANX
                    driver.mkdir(Path(physical_locus).parent, parents=True, exist_ok=True)

                    p = Path(physical_locus)
                    temp_p = p.with_name(f".{p.name}.{uuid.uuid4().hex[:6]}.tmp")

                    try:
                        with open(temp_p, 'wb') as f:
                            f.write(final_content_bytes)
                            f.flush()
                            if hasattr(os, 'fsync'): os.fsync(f.fileno())

                        max_retries = 5 if os.name == 'nt' else 1
                        for attempt in range(max_retries):
                            try:
                                os.replace(temp_p, p)
                                break
                            except OSError:
                                if attempt == max_retries - 1: raise
                                time.sleep(0.05 * (2 ** attempt))
                    finally:
                        if temp_p.exists(): temp_p.unlink(missing_ok=True)

                    # Consecration
                    mode = self._resolve_permissions(metadata.get('permissions'))
                    driver.chmod(str(p), mode)
                    self._stamp_lineage(p, trace_id)

                duration_ms = (time.perf_counter() - _start_ns) / 1_000_000
                return GnosticWriteResult(
                    success=True, path=Path(transmuted_path), action_taken=action,
                    bytes_written=len(final_content_bytes), gnostic_fingerprint=new_hash,
                    duration_ms=duration_ms,
                    metadata={"driver": "VFS" if self.vfs else driver.kind.name, "trace_id": trace_id}
                )

            except Exception as catastrophic_paradox:
                if not isinstance(catastrophic_paradox, ArtisanHeresy):
                    Logger.error(f"Inscription fractured for '{path_str}': {catastrophic_paradox}")
                return GnosticWriteResult(
                    success=False, path=Path(path_str), action_taken=InscriptionAction.FAILED_IO,
                    error=str(catastrophic_paradox), duration_ms=(time.perf_counter() - _start_ns) / 1_000_000
                )

    def _perform_atomic_write(self, driver: Any, physical_locus: str, final_content_bytes: bytes):
        """
        [ASCENSION 4 & 5]: QUANTUM ATOMIC PERSISTENCE.
        Writes to a `.tmp` file, calls fsync to flush hardware buffers, and
        performs an atomic os.replace to guarantee ACID compliance. Includes
        WinError 32 exponential backoff.
        """
        # If the driver is a custom wrapper (e.g., SSHSanctum), we delegate to it
        if hasattr(driver, 'write_bytes_atomic'):
            driver.write_bytes_atomic(physical_locus, final_content_bytes)
            return

        # Standard Local File System Atomic Write
        import uuid
        p = Path(physical_locus)
        temp_path = p.with_name(f".{p.name}.{uuid.uuid4().hex[:6]}.tmp")

        try:
            with open(temp_path, 'wb') as f:
                f.write(final_content_bytes)
                f.flush()
                # Ensure OS buffers are flushed to hardware disk cache
                if hasattr(os, 'fsync'):
                    try:
                        os.fsync(f.fileno())
                    except OSError:
                        pass

            # The WinError 32 Phalanx (Exponential Backoff for file locks)
            max_retries = 5 if self.is_windows else 1
            for attempt in range(max_retries):
                try:
                    os.replace(temp_path, p)
                    return
                except OSError as e:
                    # Windows Error 32: The process cannot access the file because it is being used by another process.
                    if attempt == max_retries - 1:
                        raise e
                    time.sleep(0.05 * (2 ** attempt))

        except Exception as e:
            if temp_path.exists():
                try:
                    temp_path.unlink()
                except:
                    pass
            raise e

    def mkdir(self, logical_path: Union[str, Path]) -> bool:
        """[THE GRAND RITE OF SANCTUM FORGING]
        """
        with self._io_lock:
            transmuted_path = self.alchemist.transmute(str(logical_path))

            # VFS Routing
            if self.vfs:
                try:
                    self.vfs.makedirs(transmuted_path.replace('\\', '/'), recreate=True)
                    return True
                except Exception as e:
                    Logger.error(f"VFS Sanctum forge failed: {e}")
                    return False

            driver, physical_locus = self.router.resolve(transmuted_path)

            if self.regs.dry_run:
                return True

            try:
                # [ASCENSION 17]: Ledger Tombstone
                # Note: TransactionManager handles atomicity for FILES, but mkdir is usually safe.
                # We record it in the ledger for replay/undo.
                entry = LedgerEntry(
                    actor="IOConductor",
                    operation=LedgerOperation.MKDIR,
                    forward_state={"path": transmuted_path, "driver": driver.kind.name},
                    inverse_action=InverseOp(op=LedgerOperation.RMDIR,
                                             params={"path": transmuted_path, "recursive": True})
                )
                ActiveLedger.record(entry)

                driver.mkdir(physical_locus, parents=True, exist_ok=True)
                return True
            except Exception as e:
                Logger.error(f"Sanctum forge failed at '{transmuted_path}': {e}")
                if not self.regs.force: raise e
                return False

    def delete(self, logical_path: Union[str, Path], recursive: bool = False):
        """[THE GRAND RITE OF ANNIHILATION]
        """
        with self._io_lock:
            transmuted_path = self.alchemist.transmute(str(logical_path))

            # VFS Routing
            if self.vfs:
                p_str = transmuted_path.replace('\\', '/')
                if self.vfs.exists(p_str):
                    if self.vfs.isdir(p_str):
                        self.vfs.removetree(p_str) if recursive else self.vfs.removedir(p_str)
                    else:
                        self.vfs.remove(p_str)
                return

            driver, physical_locus = self.router.resolve(transmuted_path)

            if not driver.exists(physical_locus):
                return

            if self.regs.dry_run:
                return

            try:
                # [THE FIX]: Transaction Register Intent for Deletion
                if self.regs.transaction:
                    tx_id = self.regs.transaction.current_tx_id
                    if tx_id:
                        self.regs.transaction.register_intent(tx_id, Path(physical_locus), 'delete')

                snapshot = None
                if not recursive and driver.is_file(physical_locus):
                    snapshot = driver.read_bytes(physical_locus)

                # [ASCENSION 17]: Ledger Tombstone
                entry = LedgerEntry(
                    actor="IOConductor",
                    operation=LedgerOperation.DELETE_FILE if not recursive else LedgerOperation.RMDIR,
                    forward_state={"path": transmuted_path, "recursive": recursive},
                    inverse_action=InverseOp(op=LedgerOperation.WRITE_FILE, params={"path": transmuted_path,
                                                                                    "content_is_snapshot": True}) if snapshot else None,
                    snapshot_content=snapshot
                )
                ActiveLedger.record(entry)

                # Trash Manager Integration (Logical Undo)
                if recursive:
                    driver.rmdir(physical_locus, recursive=True)
                else:
                    driver.unlink(physical_locus)

            except Exception as e:
                Logger.error(f"Annihilation failed for '{transmuted_path}': {e}")
                if not self.regs.force: raise e

    def move(self, src: Union[str, Path], dest: Union[str, Path]) -> bool:
        """[THE RITE OF TRANSLOCATION]"""
        with self._io_lock:
            t_src = self.alchemist.transmute(str(src))
            t_dest = self.alchemist.transmute(str(dest))
            d_src, p_src = self.router.resolve(t_src)
            d_dest, p_dest = self.router.resolve(t_dest)

            if self.regs.dry_run: return True

            if d_src.kind != d_dest.kind:
                Logger.info(f"Cross-Reality Translocation: {d_src.kind.name} -> {d_dest.kind.name}")
                try:
                    d_src.project_to(d_dest, p_src, p_dest)
                    d_src.rmdir(p_src, recursive=True) if d_src.is_dir(p_src) else d_src.unlink(p_src)
                    return True
                except Exception as e:
                    Logger.error(f"Cross-Reality Translocation fractured: {e}")
                    return False
            try:
                ActiveLedger.record(LedgerEntry(
                    actor="IOConductor",
                    operation=LedgerOperation.RENAME,
                    forward_state={"src": t_src, "dest": t_dest},
                    inverse_action=InverseOp(op=LedgerOperation.RENAME, params={"src": t_dest, "dest": t_src})
                ))
                d_src.rename(p_src, p_dest)
                return True
            except Exception as e:
                Logger.error(f"Translocation failed: {e}")
                return False

    def chmod(self, logical_path: Union[str, Path], mode: Union[int, str]) -> bool:
        """
        =============================================================================
        == THE RITE OF CONSECRATION (V-Ω-TOTALITY-V18-CHMOD)                       ==
        =============================================================================
        LIF: 20x | ROLE: ACCESS_WARDEN | RANK: MASTER

        Transmutes the access permissions of a physical or virtual scripture.
        Mathematically warded against permission-drift via the Gnostic Ledger.
        """
        with self._io_lock:
            # 1. GEOMETRIC NORMALIZATION
            transmuted_path = self.alchemist.transmute(str(logical_path))

            # [ASCENSION 1]: VFS PASSIVE BYPASS
            # Virtual filesystems often lack physical permission strata; we accept and skip.
            if self.vfs:
                # self.Logger.debug(f"VFS Consecration: {transmuted_path} -> {mode} [VIRTUAL_ONLY]")
                return True

            # 2. RESOLVE REALITY DRIVER
            driver, physical_locus = self.router.resolve(transmuted_path)

            # 3. PROPHECY CHECK (DRY RUN)
            if self.regs.dry_run:
                # self.Logger.verbose(f"[DRY-RUN] Consecrating {transmuted_path} with mode {mode}")
                return True

            try:
                # 4. THE LEDGER VOW (CHRONICLE INSCRIPTION)
                # We attempt to scry the old mode for reversible alchemy
                old_mode = None
                if driver.exists(physical_locus):
                    try:
                        old_mode = oct(os.stat(physical_locus).st_mode & 0o777)
                    except Exception:
                        pass

                ActiveLedger.record(LedgerEntry(
                    actor="IOConductor",
                    operation=LedgerOperation.CHMOD,
                    forward_state={"path": transmuted_path, "mode": str(mode)},
                    inverse_action=InverseOp(op=LedgerOperation.CHMOD,
                                             params={"path": transmuted_path, "mode": old_mode}) if old_mode else None
                ))

                # 5. THE KINETIC STRIKE
                # Handle semantic mapping (e.g. '755' vs 0o755)
                final_mode = self._resolve_permissions(mode)

                # Apply Windows Ward for path length safety
                final_locus = self._apply_windows_ward(str(physical_locus))

                driver.chmod(final_locus, final_mode)
                return True

            except Exception as e:
                Logger.error(f"Consecration failed for '{transmuted_path}': {e}")
                if not self.regs.force: raise e
                return False


    def _divine_magic_number(self, data: bytes, path: Path):
        """Verifies binary integrity via Magic Numbers."""
        if len(data) < 4: return
        magic = data[:4]
        ext = path.suffix.lower()
        if ext == '.png' and magic != b'\x89PNG':
            Logger.warn(f"Magic Number Mismatch: '{path.name}' claims to be PNG but lacks signature.")
        elif ext == '.zip' and magic[:2] != b'PK':
            Logger.warn(f"Magic Number Mismatch: '{path.name}' claims to be ZIP but lacks signature.")

    def _adjudicate_lfs_ward(self, data: bytes, path: Path):
        """The Git LFS Oracle."""
        if len(data) > self.LFS_MASS_THRESHOLD:
            Logger.warn(f"Massive Binary Detected ({len(data)}B). The Oracle advises Git LFS for '{path.name}'.")

    def _heal_python_imports(self, content: str) -> str:
        """The Auto-Import Healer."""
        lines = content.splitlines()
        existing_imports = set()
        for line in lines:
            if line.strip().startswith(("import ", "from ")):
                existing_imports.add(line.strip())

        injected_imports = []
        for symbol, import_stmt in self.IMPORT_HEALING_MAP.items():
            if re.search(rf"\b{symbol}\b", content):
                is_present = False
                for imp in existing_imports:
                    if symbol in imp:
                        is_present = True
                        break
                if not is_present:
                    injected_imports.append(import_stmt)

        if not injected_imports: return content

        insert_idx = 0
        for i, line in enumerate(lines):
            if line.startswith("#") or not line.strip():
                insert_idx = i + 1
            else:
                break

        for imp in reversed(injected_imports):
            lines.insert(insert_idx, imp)

        return "\n".join(lines) + "\n"

    def _enforce_ast_formatting(self, path: Path, data: bytes) -> bytes:
        """Invokes external formatters."""
        if os.environ.get("SCAFFOLD_AUTOFORMAT") != "1" or self.is_wasm: return data
        ext = path.suffix.lower()
        try:
            if ext == '.py' and shutil.which('black'):
                res = subprocess.run(['black', '-q', '-'], input=data, capture_output=True, timeout=3)
                if res.returncode == 0: return res.stdout
            elif ext in ('.ts', '.tsx', '.js', '.jsx', '.json') and shutil.which('prettier'):
                res = subprocess.run(['prettier', '--stdin-filepath', path.name], input=data, capture_output=True,
                                     timeout=3)
                if res.returncode == 0: return res.stdout
        except:
            pass
        return data

    def _stamp_lineage(self, path: Path, trace_id: str):
        """ADS Metadata Stamping."""
        if self.is_wasm: return
        if self.is_windows:
            try:
                ads_path = str(path) + ":scaffold_trace"
                with open(ads_path, 'w') as f:
                    f.write(trace_id)
            except:
                pass

    def _apply_windows_ward(self, path_str: str) -> str:
        """Defeats the 260-char wall on Windows Iron."""
        if not self.is_windows or self.is_wasm:
            return path_str
        try:
            abs_path = os.path.abspath(path_str)
            if abs_path.startswith('\\\\?\\'):
                return abs_path
            if len(abs_path) < 240:
                return abs_path
            if abs_path.startswith('\\\\'):
                return '\\\\?\\UNC\\' + abs_path[2:]
            return '\\\\?\\' + abs_path
        except Exception as e:
            Logger.debug(f"Long-Path Phalanx deferred for '{path_str[:30]}...': {e}")
            return path_str

    def _resolve_permissions(self, perms_meta: Optional[Union[str, int]]) -> int:
        """Transmutes semantic or octal intent into physical mode integers."""
        if perms_meta is None or perms_meta == "":
            return 0o644
        if self.is_wasm or self.is_windows:
            return 0o644
        try:
            if isinstance(perms_meta, str):
                plea = perms_meta.lower().strip()
                GRIMOIRE = {
                    "executable": 0o755, "bin": 0o755, "script": 0o755,
                    "readonly": 0o444, "secret": 0o600, "private": 0o600,
                    "public": 0o644, "internal": 0o640, "shard": 0o666
                }
                if plea in GRIMOIRE: return GRIMOIRE[plea]
                if re.match(r'^[0-7]{3,4}$', plea): return int(plea, 8)
                if plea.startswith('0o'): return int(plea, 8)
            if isinstance(perms_meta, int):
                return perms_meta
            return 0o644
        except Exception as paradox:
            self.Logger.debug(f"Permission Adjudication deferred for '{perms_meta}': {paradox}")
            return 0o644

    def _apply_immutable_ward(self, path: Path):
        if self.is_wasm or self.is_windows: return
        try:
            subprocess.run(['chattr', '+i', str(path)], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
            Logger.info(f"Immutable Ward applied to '{path.name}'.")
        except Exception:
            pass

    def _trigger_live_reload_pulse(self, logical_path: Path):
        """Touches a signal file for dev servers."""
        if self.is_wasm: return
        try:
            pulse_file = self.project_root / ".scaffold" / ".reload_pulse"
            pulse_file.parent.mkdir(parents=True, exist_ok=True)
            pulse_file.touch(exist_ok=True)
        except:
            pass

    def _forge_result(self, path: Path, success: bool, action: InscriptionAction, bytes_written: int,
                      hash_sig: Optional[str], diff: Optional[str], alerts: list,
                      start_time: float) -> GnosticWriteResult:
        """Standardizes the output payload."""
        mime_type, _ = mimetypes.guess_type(str(path))
        return GnosticWriteResult(
            success=success, path=path, action_taken=action, bytes_written=bytes_written,
            gnostic_fingerprint=hash_sig, diff=diff, security_notes=alerts,
            duration_ms=(time.perf_counter() - start_time) * 1000,
            metadata={"mime_type": mime_type or "application/octet-stream"}
        )

    def __repr__(self) -> str:
        return f"<Ω_IO_CONDUCTOR substrate={'VFS_RAM' if self.vfs else ('ETHER' if self.is_wasm else 'IRON')}>"