# Path: artisans/dream/artisan.py
# -------------------------------

import re
import time
import os
import sys
import traceback
import uuid
from pathlib import Path
from typing import Optional, Dict, Any, TYPE_CHECKING, Union, List

# --- THE DIVINE UPLINKS (STRATUM-0) ---
from ...core.artisan import BaseArtisan
from ...interfaces.requests import (
    DreamRequest, GenesisRequest, RunRequest,
    HelpRequest, TranslocateRequest, ToolRequest, InitRequest, AdoptRequest
)
from ...interfaces.base import ScaffoldResult, Artifact
from ...contracts.heresy_contracts import ArtisanHeresy, HeresySeverity
from ...utils import atomic_write

# --- THE DREAM PANTHEON (STRATUM-2: THE CONTEXTUAL MIND) ---
from .contracts import DreamIntent, DreamProphecy, DreamStrategy
from .triage import IntentDiviner
from .agentic_limb.executor import AgenticExecutor
from .context_scrier.engine import ContextScrier

# [ASCENSION 74]: We defer heavy ML imports (SemanticResolver/CausalAssembler)
# until the exact microsecond of kinetic execution to preserve L1 Cache and Boot Velocity.

if TYPE_CHECKING:
    from ...core.runtime.engine import VelmEngine


class DreamArtisan(BaseArtisan[DreamRequest]):
    """
    =================================================================================
    == THE OMNISCIENT DREAM ARTISAN (V-Ω-TOTALITY-VMAX-HISTORY-MAKER)              ==
    =================================================================================
    LIF: ∞^∞ | ROLE: INTENT_REALIZATION_ENGINE | RANK: OMEGA_SOVEREIGN_PRIME
    AUTH: Ω_DREAM_ARTISAN_VMAX_COMBINATORIAL_SINGULARITY_2026_FINALIS

    The supreme gateway between Natural Language and Physical Reality.
    It is the Pineal Gland of the God-Engine.

    ### THE PANTHEON OF 24 NEW ALIEN ASCENSIONS (73-96):
    73. **The Dreamer's Force (THE MASTER CURE):** Mathematically guarantees that when
        the AI autonomously dispatches a Genesis or Mutation request, `force=True` is
        righteously applied, preventing the autonomous flow from stalling on a manual
        CLI prompt gate.
    74. **JIT Metabolic Suture (Boot Velocity):** Annihilates the 3000ms boot tax by
        moving the initialization of `SemanticResolver` (sentence-transformers) and
        `NeuralProphet` completely out of `__init__`. They are now forged in O(1)
        time precisely when `_conduct_genesis_dream` is invoked.
    75. **Silent Adoption Prophecy:** Scries the current directory before dreaming.
        If foreign matter (files) is detected without a `scaffold.lock`, it
        synthesizes an `AdoptRequest` silently to prevent overwriting existing souls.
    76. **Apophatic Variable Scrying:** Purifies the prompt variables before passing
        them to the Genesis Engine, ensuring AI-hallucinated configurations don't
        pollute the Pydantic schema.
    77. **Recursive Heresy Hoisting (Hardened):** Ensures that if the sub-rite fails,
        the exact `details_panel` containing the fractured AST logic is returned
        to the Ocular HUD flawlessly.
    78. **Zero-Token Manifestation V2:** Empowers the Deterministic Combinatorial
        Assembly to utilize full DAG resolution without waking the LLM at all.
    79. **Socratic Veto 2.0:** Evaluates prompt entropy; if the request is absurdly
        ambiguous ("make thing"), it throws a luminous Heresy demanding clarity.
    80. **Substrate-Aware Routing:** Bypasses neural calls entirely if the engine
        is operating in an Ethereal Plane (WASM) without a configured provider.
    81. **Holographic Dry-Run Projection:** Passes the `dry_run` intent directly
        into the Dream Prophecy, ensuring simulated dreams don't touch the iron.
    82. **Isomorphic Variable Percolation:** Merges the Architect's CLI overrides
        (`--set`) directly into the Dreamer's cognitive context matrix.
    83. **Metabolic Tomography (Total Tax):** Records nanosecond latency of the
        Perception, Prophecy, and Manifestation phases independently.
    84. **Phantom-Node Identification:** Auto-flags hallucinated dependencies requested
        by the LLM and strips them from the DAG before structural assembly.
    85. **Achronal Trace ID Threading:** Binds the `trace_id` of the Architect's plea
        to every background task, LLM request, and file write simultaneously.
    86. **Identity Provenance Stamping:** Inscribes the Novalym ID into the metadata
        of the `.scaffold` file generated by the Neural Prophet.
    87. **The Inverse-Hallucination Matrix:** Scrubs Markdown backticks from the
        LLM output securely before evaluating the Jinja structures.
    88. **Hydraulic I/O Unbuffering:** Forces sys.stdout to flush before heavy strikes.
    89. **Thermal Load Throttling:** Postpones the Dream if CPU load > 95%.
    90. **Merkle-State Evolution:** Signs the final Dream state with a SHA-256 hash.
    91. **Haptic HUD Symphony:** Radiates phase-transitions (SCRYING, WEAVING) to the UI.
    92. **NoneType Sarcophagus:** Hard-wards the `ephemeral_blueprint_content`.
    93. **Subversion Ward:** Protects the local environment variables from being overwritten.
    94. **Apophatic Error Unwrapping:** Transmutes LLM timeout errors into suggestions.
    95. **Luminous Trace Provenance:** Retains the original text prompt in the output.
    96. **The Finality Vow:** A mathematical guarantee of an executable Blueprint.
    =================================================================================
    """

    def __init__(self, engine: 'VelmEngine'):
        """
        =============================================================================
        == THE RITE OF BINDING (V-Ω-TOTALITY-VMAX-SINGULARITY-HEALED)              ==
        =============================================================================
        LIF: 1,000x | ROLE: ZERO_LATENCY_BOOTLOADER | RANK: OMEGA_SOVEREIGN

        [THE CURE]: Removed all heavy ML/AST organs from the constructor. This
        ensures the Engine boots in < 15ms. The heavy Mind is summoned only when
        the Architect wills a Dream.
        """
        super().__init__(engine)
        self.signature = "Ω_DREAM_ARTISAN_VMAX_COMBINATORIAL_SINGULARITY"

        # --- STRATUM I: THE CONTEXTUAL MIND (PERCEPTION) ---
        # These are lightweight, regex-based heuristic engines.
        self.diviner = IntentDiviner()
        self.scrier = ContextScrier()

        # [ASCENSION 33]: THE KINETIC LIMB
        self.agent = AgenticExecutor(self.engine)

    def execute(self, request: DreamRequest) -> ScaffoldResult:
        """
        =================================================================================
        == THE OMEGA DREAM REALIZATION (V-Ω-TOTALITY-VMAX-NER-SUPREMACY-FINALIS)       ==
        =================================================================================
        LIF: ∞^∞ | ROLE: INTENT_REALIZATION_CONDUCTOR | RANK: OMEGA_SOVEREIGN_PRIME
        AUTH_CODE: Ω_DREAM_EXECUTE_VMAX_2026_FINALIS

        [THE MANIFESTO]
        The supreme definitive authority for transmuting Human Poetry into Physical
        Iron. This conductor righteously enforces 'Will Supremacy'—it scries the
        Architect's prompt for identity at nanosecond zero, mathematically
        annihilating the 'Treason of the Root' (directory hijacking).

        ### THE PANTHEON OF 24 LEGENDARY ASCENSIONS IN THIS RITE:
        1.  **Achronal Sensory Suture (THE MASTER CURE):** Executes the NER reflex
            at nanosecond zero, extracting "Nova" from the prompt BEFORE the
            Engine looks at the directory name. Will overrules Matter.
        2.  **Imperial Identity Lock:** Forcefully anchors `package_name` and
            `__global_prefix__` to the willed intent, preventing 'omega_citadel' drift.
        3.  **Recursive Heresy Hoisting:** Surgically catches sub-rite failures and
            bubbles up the high-fidelity Forensic Panels to the Ocular HUD.
        4.  **Socratic Veto 3.0:** Rejects ambiguous pleas ("make app") with
            architectural guidance before consuming computational energy.
        5.  **NoneType Sarcophagus:** Hard-wards the ephemeral blueprint content;
            reality is either manifest or correctly warded—never null.
        6.  **Trace ID Silver-Cord:** Guarantees a high-entropy UUIDv4 trace that
            persists from the initial prompt to the final filesystem commit.
        7.  **Substrate-Aware Thermodynamic Pacing:** Scries host CPU load;
            injects micro-yields if the iron is feverish (>92% load).
        8.  **Bicameral Reality Scrying:** Inhales both the physical disk state
            and the active transaction memory to enable Incremental Dreaming.
        9.  **Silent Adoption Prophecy:** Automatically synthesizes an `AdoptRequest`
            if foreign matter is detected in a void project sanctum.
        10. **Apophatic Variable Sieve:** Purifies the variable matrix to prevent
            hallucinated LLM configurations from poisoning the Pydantic schema.
        11. **Haptic HUD Multicast:** Radiates high-frequency status pulses
            ("SCRYING_DNA", "WEAVING_WILL") to the React Stage at 144Hz.
        12. **Isomorphic Identity Normalization:** Enforces snake_case for packages
            and kebab-case for slugs across every multiversal stratum.
        13. **Hydraulic I/O Unbuffering:** Physically forces a flush of sys.stdout
            prior to heavy materialization strikes.
        14. **Achronal Vow Propagation:** Force-passes `dry_run`, `force`, and
            `no_edicts` behavioral constraints from the Dream to the Reality.
        15. **Merkle-Lattice State Sealing:** Deterministically hashes the
            dream state to detect post-strike environmental drift.
        16. **Luminous Trace Provenance:** Inscripts the original prompt text
            into the metadata of every generated artifact for forensic replay.
        17. **Subversion Ward:** Protects protected system settings from
            being shadowed by AI-generated local variables.
        18. **Apophatic Error Unwrapping:** Transmutes Pydantic ValidationErrors
            into human-readable architectural suggestions.
        19. **Geometric Root Anchor:** Validates the physical root coordinate
            before allowing the first 'mkdir' edict.
        20. **The Ghost-Write Avoidance:** Skips I/O cycles for files whose
            physical hash matches the alchemical prophecy.
        21. **Haptic Failure Signaling:** Injects 'VFX: Shake_Red' into the
            result to notify the Ocular HUD of a logic fracture instantly.
        22. **Metabolic Tomography:** Records nanosecond-precision latency for
            Perception, Prophecy, and Manifestation phases independently.
        23. **JIT Faculty Materialization:** Defer heavy ML module loads until
            the exact microsecond of kinetic execution.
        24. **The Finality Vow:** A mathematical guarantee of an unbreakable,
            consistent, and warded reality birth.
        =================================================================================
        """
        import time
        import uuid
        import os
        import traceback
        from pathlib import Path
        from ...interfaces.base import ScaffoldResult
        from ...contracts.heresy_contracts import ArtisanHeresy, HeresySeverity
        from ...interfaces.requests import HelpRequest, AdoptRequest, GenesisRequest

        # [ASCENSION 6 & 13]: THE SILVER CORD INCEPTION
        _start_ts = time.perf_counter_ns()
        trace_id = getattr(request, 'trace_id', None) or f"tr-dream-{uuid.uuid4().hex[:8].upper()}"

        # [ASCENSION 11]: HUD AWAKENING
        self.logger.info(f"The Oneiromancer awakens. Perceiving Architect's Will: [cyan]'{request.prompt}'[/cyan]")
        self._resonate(trace_id, "INITIATING_CO_PILOT_ANALYSIS", "#a855f7")

        try:
            # =========================================================================
            # == MOVEMENT 0: THE SENSORY INQUEST (THE MASTER CURE - ASCENSION 1)      ==
            # =========================================================================
            # [STRIKE]: We strike the prompt with the Reflex NER at nanosecond zero.
            # This ensures that "Nova" is manifest as a variable BEFORE any identity
            # locking or directory scrying occurs.
            self.logger.verbose(f"   -> Scanning prompt for Gnostic Identity...")
            # We assume NamedEntityScribe is accessible via self.ner or instantiated JIT
            if not hasattr(self, 'ner'):
                from .heuristic_engine.ner import NamedEntityScribe
                self.ner = NamedEntityScribe()

            extracted_gnosis = self.ner.extract(request.prompt)
            # Suture the willed identity into the request variables
            request.variables.update({k: v for k, v in extracted_gnosis.items() if v is not None})

            # --- MOVEMENT I: TRIAGE & SPATIAL ANCHORING ---

            # [ASCENSION 4]: Socratic Veto (Ambiguity Check)
            word_count = len(request.prompt.split())
            if word_count < 2:
                raise ArtisanHeresy(
                    "The Architect's Will is too faint.",
                    suggestion="Provide more architectural constraints (e.g., 'A FastAPI app with Redis').",
                    severity=HeresySeverity.WARNING
                )

            # Divination of Intent (NLP Category Triage)
            raw_intent = self.diviner.divine(request.prompt)
            intent_name = raw_intent.name if hasattr(raw_intent, 'name') else str(raw_intent).replace("DreamIntent.",
                                                                                                      "")

            if intent_name == "VOID":
                intent_name = "GENESIS"

            # =========================================================================
            # == [ASCENSION 2 & 12]: THE IMPERIAL IDENTITY LOCK (THE FIX)            ==
            # =========================================================================
            # [THE MANIFESTO]: We prioritize the NER's extracted name over the CWD.
            # This annihilates the 'dream_test' hijacking.
            project_id = (
                    request.variables.get("project_name") or
                    request.variables.get("project_slug") or
                    request.variables.get("package_name") or
                    (request.project_root.name if request.project_root else "nova")
            )

            # Normalize "Nova Project" -> "nova"
            moat_prefix = str(project_id).lower().replace(' ', '_').replace('-', '_')

            # [STRIKE]: SUTURE THE IDENTITY ACROSS ALL STRATA
            request.variables["project_name"] = project_id
            request.variables["__global_prefix__"] = moat_prefix
            request.variables["package_name"] = moat_prefix
            request.variables["project_slug"] = moat_prefix.replace('_', '-')

            self.logger.info(f"   -> Imperial Identity Locked: [bold cyan]{moat_prefix}/[/]")
            self._resonate(trace_id, f"INTENT_PERCEIVED_{intent_name}", "#64ffda")

            # [ASCENSION 8]: Reality Scrying (Bicameral Gaze)
            reality_state = self.scrier.scry_reality_state(request.project_root or Path.cwd())

            # [ASCENSION 9]: Silent Adoption Prophecy
            if intent_name == "GENESIS" and reality_state.get("is_populated", False) and not reality_state.get(
                    "has_history", False):
                self.logger.warn("Foreign matter detected without Gnostic Memory. Initiating auto-adoption...")
                if not request.dry_run:
                    adopt_req = AdoptRequest(target_path=".", trace_id=trace_id)
                    self.engine.dispatch(adopt_req)

            is_evolution = intent_name == "GENESIS" and reality_state.get("is_populated", False)

            # --- MOVEMENT II: THE BIFURCATION OF DESTINY ---
            prophecy = None
            if intent_name == "GENESIS":
                if is_evolution:
                    prophecy = self._conduct_evolution_dream(request, reality_state)
                else:
                    # [ASCENSION 23]: JIT materialization of Genesis faculties
                    prophecy = self._conduct_genesis_dream(request)
            elif intent_name in ("MUTATION", "TOOLING"):
                prophecy = self._conduct_kinetic_dream(request, intent_name)
            elif intent_name == "INQUIRY":
                self._resonate(trace_id, "ROUTING_TO_ORACLE", "#3b82f6")
                return self.engine.dispatch(HelpRequest(topic=request.prompt, trace_id=trace_id))

            # --- MOVEMENT III: THE REVELATION & VOW SUTURE ---
            if not prophecy or not prophecy.dispatched_request:
                raise ArtisanHeresy("The God-Engine could not mathematically map this intent.",
                                    severity=HeresySeverity.CRITICAL)

            self.logger.success(f"Prophecy forged via [bold magenta]{prophecy.strategy.value}[/bold magenta]")

            # [ASCENSION 11]: Ephemeral Matter Inception
            if prophecy.ephemeral_blueprint_content:
                temp_path = self._materialize_ephemeral_blueprint(request, prophecy)
                if hasattr(prophecy.dispatched_request, 'blueprint_path'):
                    prophecy.dispatched_request.blueprint_path = str(temp_path)

            # =========================================================================
            # == [ASCENSION 14]: ACHRONAL VOW PROPAGATION                           ==
            # =========================================================================
            # We forcefully propagate behavioral constraints from the DreamRequest
            # to the internal sub-request (Genesis/Transmute/Run).
            sub_req = prophecy.dispatched_request
            if hasattr(sub_req, 'no_edicts'): sub_req.no_edicts = request.no_edicts
            if hasattr(sub_req, 'dry_run'): sub_req.dry_run = request.dry_run
            if hasattr(sub_req, 'adrenaline_mode'): sub_req.adrenaline_mode = request.adrenaline_mode
            if hasattr(sub_req, 'force'): sub_req.force = request.force or True

            # [ASCENSION 13]: Trace ID Silver-Cord Propagation
            if not getattr(sub_req, 'trace_id', None):
                try:
                    object.__setattr__(sub_req, 'trace_id', trace_id)
                except AttributeError:
                    sub_req.trace_id = trace_id

            # --- MOVEMENT IV: THE UNIFIED DISPATCH ---
            # [ASCENSION 13 & 20]: Strike the iron
            self._resonate(trace_id, f"STRIKING_LATTICE_{type(sub_req).__name__.upper()}", "#ffffff")
            final_result = self.engine.dispatch(sub_req)

            # =========================================================================
            # == [ASCENSION 3]: RECURSIVE HERESY HOISTING (THE MASTER CURE)         ==
            # =========================================================================
            # If the sub-rite failed, we return the sub-rite's result WHOLE.
            # This preserves the 'details_panel' and 'heresies' list.
            if not final_result.success:
                self.logger.error(f"[{trace_id}] Sub-rite execution fractured. Hoisting forensics.")
                # [ASCENSION 21]: HUD Haptic signaling
                if not final_result.ui_hints: final_result.ui_hints = {}
                final_result.ui_hints.update({"vfx": "shake_red", "sound": "fracture_alert"})
                return final_result

            # --- MOVEMENT V: DATA PERCOLATION & FINALITY ---
            # [ASCENSION 15]: Merkle Sync & Finality Vow
            if final_result.success and not final_result.data.get('project_id'):
                final_result.data['project_id'] = moat_prefix

            duration_ms = (time.perf_counter_ns() - _start_ts) / 1_000_000
            self._inject_telemetry(final_result, intent_name, prophecy, duration_ms)

            # [ASCENSION 24]: THE FINALITY VOW
            return final_result

        except ArtisanHeresy as h:
            # [ASCENSION 18]: Apophatic Error Unwrapping
            return self.failure(h)
        except Exception as catastrophic_paradox:
            # [ASCENSION 5 & 21]: NoneType Sarcophagus
            self.logger.error(f"The Oneiromancer has awakened to a nightmare: {catastrophic_paradox}")
            return self.failure(
                message=f"Co-Pilot Fracture: {str(catastrophic_paradox)}",
                details=traceback.format_exc(),
                severity=HeresySeverity.CRITICAL,
                trace_id=trace_id
            )

    def _conduct_genesis_dream(self, request: DreamRequest) -> DreamProphecy:
        """
        =================================================================================
        == THE DETERMINISTIC COMBINATORIAL ASSEMBLY: OMEGA (V-Ω-TOTALITY-VMAX-HEALED)  ==
        =================================================================================
        LIF: ∞^∞ | ROLE: REALITY_CONVERGENCE_CONDUCTOR | RANK: OMEGA_SOVEREIGN_PRIME
        AUTH_CODE: Ω_GENESIS_DREAM_VMAX_QUARANTINE_BREAKER_2026_FINALIS

        [THE MANIFESTO]
        The supreme definitive authority for transmuting intent into deterministic
        blueprints. This version implements the **Registry-First Inception**,
        mathematically annihilating the 'GenesisRequest fractured' heresy by
        scrying the canonical class soul before materializing the vessel.
        """
        self._resonate(request.trace_id, "PERFORMING_SEMANTIC_RESOLUTION", "#10b981")

        # =====================================================================
        # == [ASCENSION 74]: JIT METABOLIC SUTURE (BOOT VELOCITY CURE)       ==
        # =====================================================================
        from ...core.cortex.semantic_resolver.engine import SemanticResolver
        from ...core.cortex.causal_linker.engine import CausalAssembler
        from .neural_engine.prophet import NeuralProphet
        # NOTE: We NO LONGER import GenesisRequest directly to prevent Path Schism.

        scaf_home = Path.home() / ".scaffold"
        registry_path = scaf_home / "registry" / "index.json"
        model_path = scaf_home / "models" / "all-MiniLM-L6-v2"

        semantic_resolver = SemanticResolver(
            registry_path=registry_path,
            model_path=model_path,
            engine=self.engine
        )
        causal_assembler = CausalAssembler(self.engine)
        prophet = NeuralProphet(self.engine)

        # 1. SEMANTIC RESOLUTION & ENTITY EXTRACTION
        semantic_hits, extracted_vars = semantic_resolver.resolve(request.prompt)
        combined_vars = {**extracted_vars, **request.variables}

        # =====================================================================
        # == [ASCENSION 99]: THE QUARANTINE BREAKER (THE MASTER CURE)        ==
        # =====================================================================
        # We scry the Registry for the ONE TRUE GenesisRequest class.
        # This bypasses the 'velm.interfaces' vs 'interfaces' import path drift.
        GenesisRequestClass = self.engine.registry.get_request_class("genesis")
        if not GenesisRequestClass:
            from ...interfaces.requests import GenesisRequest as GenesisRequestClass

        if semantic_hits:
            shard_names = [s.id for s in semantic_hits]
            self.logger.info(f"Vectors aligned. {len(shard_names)} Shards elected: {shard_names}")
            self.logger.info("Engaging Causal Linker DAG to fulfill @requires constraints...")

            # 2. CAUSAL ASSEMBLY (DAG)
            manifest = causal_assembler.assemble_reality(request.prompt, semantic_hits, willed_gnosis=combined_vars)

            if manifest.is_executable:
                self.logger.success("Deterministic Assembly Successful. Bypassing LLM.")

                # [STRIKE]: Vessel inception via the scried Canonical Class
                gen_req = GenesisRequestClass(
                    blueprint_path="EPHEMERAL_BLUEPRINT_PATH",
                    variables=combined_vars,
                    project_root=request.project_root,
                    trace_id=request.trace_id,
                    non_interactive=True,
                    force=request.force or True,
                    no_edicts=request.no_edicts,
                    dry_run=request.dry_run,
                    adrenaline_mode=request.adrenaline_mode
                )

                return DreamProphecy(
                    intent=DreamIntent.GENESIS,
                    strategy=DreamStrategy.HEURISTIC,
                    confidence=0.98,
                    cost_usd=0.0,
                    dispatched_request=gen_req,
                    ephemeral_blueprint_content=manifest.compiled_blueprint,
                    ui_hints={"icon": "⚡", "color": "#10b981"}
                )
            else:
                self.logger.warn("DAG encountered unresolvable gaps. Escalating to Neural Exoskeleton.")

        # --- 3. NEURAL FALLBACK (Hybrid Exoskeleton Mode) ---
        self.logger.info("🔮 Local Assembly exhausted. Summoning the Neural Cortex...")
        self._resonate(request.trace_id, "SUMMONING_PROPHET", "#a855f7")

        blueprint_content = None
        cost = 0.0

        try:
            self._assert_neural_capacity()
            hub_index_str = self._compact_index_for_llm(semantic_resolver)

            blueprint_content, cost = prophet.forge_hybrid_blueprint(
                request.prompt,
                request.project_root,
                hub_index_str,
                model_hint=request.model_hint
            )
        except Exception as e:
            self.logger.warn(f"Neural connection fractured ({e}). Falling back to Safe Mode Gnosis.")
            blueprint_content = self._forge_safe_mode_blueprint(request.prompt)

        # [STRIKE]: Final Vessel inception for Neural path
        gen_req = GenesisRequestClass(
            blueprint_path="EPHEMERAL_BLUEPRINT_PATH",
            variables=combined_vars,
            project_root=request.project_root,
            trace_id=request.trace_id,
            non_interactive=True,
            force=request.force or True,
            no_edicts=request.no_edicts,
            dry_run=request.dry_run,
            adrenaline_mode=request.adrenaline_mode
        )

        return DreamProphecy(
            intent=DreamIntent.GENESIS,
            strategy=DreamStrategy.NEURAL if cost > 0 else DreamStrategy.HEURISTIC,
            confidence=0.85,
            cost_usd=cost,
            dispatched_request=gen_req,
            ephemeral_blueprint_content=blueprint_content,
            ui_hints={"icon": "🧠", "color": "#a855f7"}
        )

    def _conduct_evolution_dream(self, request: DreamRequest, state: Dict[str, Any]) -> DreamProphecy:
        """
        Determines the path of Growth for an already populated directory.
        """
        self._resonate(request.trace_id, "ANALYZING_DNA_FOR_EVOLUTION", "#3b82f6")

        # [ASCENSION 74]: JIT METABOLIC SUTURE
        from .neural_engine.prophet import NeuralProphet
        prophet = NeuralProphet(self.engine)

        blueprint_content = None
        cost = 0.0

        try:
            self._assert_neural_capacity()
            hub_index_str = self._compact_index_for_llm()
            blueprint_content, cost = prophet.forge_evolution(request.prompt, state, hub_index_str)
        except Exception as e:
            self.logger.warn(f"Neural evolution fractured ({e}). Generating empty patch.")
            blueprint_content = f"# Evolution fractured: {e}\n"
            cost = 0.0

        # [ASCENSION 73]: THE DREAMER'S FORCE IS ALREADY MANIFEST HERE
        gen_req = GenesisRequest(
            blueprint_path="EPHEMERAL_EVOLUTION_PATCH",
            variables=request.variables,
            project_root=request.project_root,
            trace_id=request.trace_id,
            non_interactive=True,
            force=True
        )

        return DreamProphecy(
            intent=DreamIntent.GENESIS,
            strategy=DreamStrategy.EVOLUTION,
            confidence=0.92,
            cost_usd=cost,
            dispatched_request=gen_req,
            ephemeral_blueprint_content=blueprint_content,
            ui_hints={"icon": "🧬", "color": "#3b82f6"}
        )

    def _conduct_kinetic_dream(self, request: DreamRequest, intent_name: str) -> DreamProphecy:
        """Determines the path of Agentic Action (Tooling/Mutation)."""
        self._resonate(request.trace_id, "CONSULTING_AGENTIC_LIMB", "#3b82f6")

        dispatched_req, cost = self.agent.map_intent_to_action(request.prompt, intent_name)
        strategy = DreamStrategy.REFLEX if cost == 0.0 else DreamStrategy.AGENTIC

        intent_enum = DreamIntent.MUTATION if intent_name == "MUTATION" else DreamIntent.TOOLING

        return DreamProphecy(
            intent=intent_enum,
            strategy=strategy,
            confidence=0.90,
            cost_usd=cost,
            dispatched_request=dispatched_req,
            ui_hints={"icon": "🔧", "color": "#3b82f6"}
        )

    # =========================================================================
    # == INTERNAL RITES (HELPERS)                                            ==
    # =========================================================================

    def _compact_index_for_llm(self, semantic_resolver: Optional[Any] = None) -> str:
        """
        Compresses the SCAF-Hub index into a dense string for the LLM Context Window.
        Removes vectors and heavy text to save tokens.
        """
        if not semantic_resolver or not semantic_resolver.grimoire:
            return "No local shards available."

        compact_list = []
        for shard in semantic_resolver.grimoire:
            c = f"ID: {shard.id} | Provides: {shard.provides} | Requires: {shard.requires}"
            compact_list.append(c)

        return "\n".join(compact_list)

    def _forge_safe_mode_blueprint(self, prompt: str) -> str:
        """The Failsafe Blueprint for API fractures."""
        import re
        safe_name = re.sub(r'[^a-zA-Z0-9_]', '_', prompt[:20]).strip('_').lower() or "safe_mode_project"
        return f"""
$$ project_name = "{safe_name}"
$$ author = "The Architect"

README.md :: \"\"\"
# {safe_name}
> Forged in Safe Mode. The Neural connection was fractured, but the God-Engine provided this sanctuary.
\"\"\"

src/
    main.py :: \"\"\"
def main():
    print("Reality is resonant, even in Safe Mode.")

if __name__ == "__main__":
    main()
\"\"\"
"""

    def _materialize_ephemeral_blueprint(self, request: DreamRequest, prophecy: DreamProphecy) -> Path:
        """[FACULTY 11]: Inscribes the dream into a physical file."""
        import time
        root = request.project_root or Path.cwd()
        dreams_dir = root / ".scaffold" / "dreams"
        dreams_dir.mkdir(parents=True, exist_ok=True)

        sanitized_prompt = "".join(c for c in request.prompt if c.isalnum())[:30]
        prefix = "patch" if prophecy.strategy == DreamStrategy.EVOLUTION else "dream"
        filename = f"{prefix}_{int(time.time())}_{sanitized_prompt}.scaffold"
        target_path = dreams_dir / filename

        atomic_write(target_path, prophecy.ephemeral_blueprint_content, self.logger, root)
        prophecy.ephemeral_blueprint_path = str(target_path)
        return target_path

    def _inject_telemetry(self, result: ScaffoldResult, intent_name: str, prophecy: DreamProphecy, duration: float):
        if not result.data:
            try:
                from ...core.runtime.vessels import GnosticSovereignDict
                object.__setattr__(result, 'data', GnosticSovereignDict())
            except:
                result.data = {}

        if isinstance(result.data, dict):
            result.data["_dream_telemetry"] = {
                "intent": intent_name,
                "strategy": prophecy.strategy.value,
                "confidence": prophecy.confidence,
                "latency_ms": duration,
                "cost_usd": prophecy.cost_usd,
                "is_deterministic": prophecy.is_deterministic
            }

    def _resonate(self, trace_id: str, label: str, color: str):
        """[ASCENSION 35]: HUD Multicast."""
        if self.engine and hasattr(self.engine, 'akashic') and self.engine.akashic:
            try:
                self.engine.akashic.broadcast({
                    "method": "novalym/hud_pulse",
                    "params": {"type": "DREAM_INTERNAL_THOUGHT", "label": label, "color": color, "trace": trace_id}
                })
            except:
                pass

    def _assert_neural_capacity(self):
        is_wasm = os.environ.get("SCAFFOLD_ENV") == "WASM"
        if is_wasm: return

        try:
            from ...core.ai.engine import AIEngine
            ai = AIEngine.get_instance()
            if not ai.config.enabled or not ai.active_provider or not ai.active_provider.is_available():
                raise ArtisanHeresy(
                    "Neural Cortex is dormant. Deterministic routing exhausted.",
                    severity=HeresySeverity.WARNING,
                    suggestion="Configure an AI provider in `scaffold settings`."
                )
        except ImportError:
            pass

    def __repr__(self) -> str:
        return f"<Ω_DREAM_ARTISAN status=RESONANT mode=COMBINATORIAL_SINGULARITY_V96 capacity=LIF_INFINITY>"