# Path: artisans/dream/contracts.py
# ---------------------------------

from __future__ import annotations
from enum import Enum, auto
from typing import Dict, Any, Optional, List, Union
from pydantic import BaseModel, Field, ConfigDict, computed_field
import time


# --- I. THE TAXONOMY OF INTENT ---

class DreamIntent(str, Enum):
    """
    The Fundamental Classifications of the Architect's Will.
    Derived by the Triage Sanctum (IntentDiviner).
    """
    GENESIS = "GENESIS"  # Creation of new reality (Blueprints)
    MUTATION = "MUTATION"  # Transformation of existing matter (Refactor/Move)
    TOOLING = "TOOLING"  # Execution of kinetic machinery (Zip/Hash/Lint)
    INQUIRY = "INQUIRY"  # Quest for wisdom (Docs/Explain)
    VOID = "VOID"  # Unknowable or Empty intent


class DreamStrategy(str, Enum):
    """The Method of Realization chosen by the Artisan."""
    HEURISTIC = "HEURISTIC"  # Deterministic, Instant, Free (Stratum 0)
    NEURAL = "NEURAL"  # Generative, Creative, Costly (Stratum 2)
    AGENTIC = "AGENTIC"  # Tool-use, Logic-driven (Stratum 3)
    REFLEX = "REFLEX"  # Regex-mapped, Zero-latency (Stratum 0)
    # [ASCENSION]: The Path of Growth
    EVOLUTION = "EVOLUTION"  # Neural Patching of existing reality

# --- II. THE VESSELS OF DISCOVERY ---

class HeuristicMatch(BaseModel):
    """
    The result of the Deterministic Heuristic Engine's scry.
    """
    model_config = ConfigDict(frozen=True)

    archetype_id: str = Field(..., description="The ID/Path of the matched archetype.")
    confidence: float = Field(..., description="Cosine similarity / TF-IDF score (0.0 to 1.0).")
    reasoning: str = Field(..., description="Why this archetype was chosen.")
    missing_variables: List[str] = Field(default_factory=list,
                                         description="Variables the blueprint needs that the prompt missed.")


class AgenticPlan(BaseModel):
    """
    The tactical plan formed by the Agentic Limb.
    """
    tool_name: str
    parameters: Dict[str, Any]
    confidence: float


# --- III. THE FINAL PROPHECY (THE RESULT) ---

class DreamProphecy(BaseModel):
    """
    =============================================================================
    == THE DREAM PROPHECY (V-Ω-EXECUTION-PLAN)                                 ==
    =============================================================================
    The finalized execution plan generated by the Dream Artisan.
    It carries the 'What', 'How', and 'Cost' of the dream before it is realized.
    """
    model_config = ConfigDict(arbitrary_types_allowed=True, extra='allow')

    # 1. The Verdict
    intent: DreamIntent
    strategy: DreamStrategy
    confidence: float

    # 2. The Payload (The Kinetic Will)
    # The actual Request object (GenesisRequest, RunRequest, etc.) to be dispatched.
    dispatched_request: Any

    # 3. The Ephemeral Matter
    # If the Neural Prophet forged a dynamic blueprint, it lives here until materialization.
    ephemeral_blueprint_content: Optional[str] = None
    ephemeral_blueprint_path: Optional[str] = None

    # 4. The Telemetry (Metabolic Tax)
    latency_ms: float = 0.0
    cost_usd: float = 0.0
    model_used: Optional[str] = None

    # 5. The Visuals
    ui_hints: Dict[str, Any] = Field(default_factory=lambda: {"icon": "🔮", "color": "#a855f7"})

    @computed_field
    @property
    def is_deterministic(self) -> bool:
        """True if the dream was resolved without Neural Inference."""
        return self.strategy in (DreamStrategy.HEURISTIC, DreamStrategy.REFLEX)